---
# Based on a template from: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml
default:
  image: docker.io/library/maven:3.8.5-openjdk-17
  cache:
    paths:
      - .m2/repository

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
    - grep "Total" target/site/jacoco/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    paths:
      - target/surefire-reports
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

deploy:
  stage: deploy
  image: docker.io/library/ruby:2.7.5-alpine3.14
  before_script:
    - apk add --no-cache build-base curl git ruby-dev
    - gem install 'dpl:2.0.2.beta.1'
  script:
    - dpl heroku api --api-key $HEROKU_API_KEY --app $HEROKU_APP_NAME
  environment:
    name: demo
    url: https://upgrade-camp-2022-example.herokuapp.com
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: manual
